# Generated by Django 4.2.3 on 2023-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='vuguy', upload_to='gal'),
            preserve_default=False,
        ),
    ]
